version: '3.9'

services:
  gateway:
    build:
      context: ../
      dockerfile: Microservices/EMS.Gateway/EMS.Gateway/Dockerfile
    container_name: ems-gateway
    restart: unless-stopped
    ports:
      - 5010:8080
    networks:
      - ems
    depends_on:
      rabbitmq:
        condition: service_healthy
        
  employees:
    build:
      context: ../
      dockerfile: Microservices/EMS.Employees/EMS.Employees/Dockerfile
    container_name: ems-employees
    restart: unless-stopped
    ports:
      - 5011:8080
    networks:
      - ems
    depends_on:
      rabbitmq:
        condition: service_healthy
        
  education:
    build:
      context: ../
      dockerfile: Microservices/EMS.Education/EMS.Education/Dockerfile
    container_name: ems-education
    restart: unless-stopped
    ports:
      - 5012:8080
    networks:
      - ems
    depends_on:
      rabbitmq:
        condition: service_healthy
        
  constacts:
    build:
      context: ../
      dockerfile: Microservices/EMS.Contracts/EMS.Contracts/Dockerfile
    container_name: ems-contracts
    restart: unless-stopped
    ports:
      - 5013:8080
    networks:
      - ems
    depends_on:
      rabbitmq:
        condition: service_healthy
      
  employee-records:
    build:
      context: ../
      dockerfile: Microservices/EMS.EmployeeRecords/EMS.EmployeeRecords/Dockerfile
    container_name: ems-employee-records
    restart: unless-stopped
    ports:
      - 5014:8080
    networks:
      - ems
    depends_on:
      rabbitmq:
        condition: service_healthy

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    networks:
      - ems
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=V22{5ntqm3X
    ports:
      - 5432:5432
    volumes:
      - ems_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    networks:
      - ems
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: V22{5ntqm3X
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on: ["postgres"]

  rabbitmq:
    image: rabbitmq:4.0-management
    networks:
      - ems
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin    
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ems_data:
  pgadmin-data:
  rabbitmq_data:
    driver: local

networks:
  ems:
    name: ems